# Generated by Django 4.0.1 on 2022-01-20 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.URLField(blank=True, db_index=True, unique=True, verbose_name='Website Link')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('sub_headline', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('livelink', models.CharField(max_length=200)),
                ('gitlink', models.CharField(max_length=200)),
                ('preview', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 20, 17, 9, 30, 174701), null=True)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('image_url', models.URLField(blank=True, max_length=250, null=True)),
                ('resume', models.URLField(blank=True, max_length=250, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='resume_builder.tag')),
            ],
        ),
    ]
