# Generated by Django 4.0.1 on 2022-01-23 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='gitlink',
        ),
        migrations.RemoveField(
            model_name='post',
            name='livelink',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='preview',
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='resume',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 23, 13, 46, 54, 678238), null=True),
        ),
        migrations.AlterField(
            model_name='socials',
            name='image_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='socials',
            name='link',
            field=models.URLField(blank=True, db_index=True, max_length=400, unique=True, verbose_name='Website Link'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stack', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=400, null=True)),
                ('livelink', models.CharField(max_length=400)),
                ('gitlink', models.CharField(max_length=400)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resume_builder.post')),
            ],
        ),
    ]
