# Generated by Django 4.0.1 on 2022-01-23 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_remove_post_description_remove_post_gitlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 23, 16, 2, 20, 54635), null=True),
        ),
    ]
